// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/libsv/payd"
	"sync"
)

// Ensure, that ProofsWriterMock does implement gopayd.ProofsWriter.
// If this is not the case, regenerate this file with moq.
var _ gopayd.ProofsWriter = &ProofsWriterMock{}

// ProofsWriterMock is a mock implementation of gopayd.ProofsWriter.
//
// 	func TestSomethingThatUsesProofsWriter(t *testing.T) {
//
// 		// make and configure a mocked gopayd.ProofsWriter
// 		mockedProofsWriter := &ProofsWriterMock{
// 			ProofCreateFunc: func(ctx context.Context, req gopayd.ProofWrapper) error {
// 				panic("mock out the ProofCreate method")
// 			},
// 		}
//
// 		// use mockedProofsWriter in code that requires gopayd.ProofsWriter
// 		// and then make assertions.
//
// 	}
type ProofsWriterMock struct {
	// ProofCreateFunc mocks the ProofCreate method.
	ProofCreateFunc func(ctx context.Context, req gopayd.ProofWrapper) error

	// calls tracks calls to the methods.
	calls struct {
		// ProofCreate holds details about calls to the ProofCreate method.
		ProofCreate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req gopayd.ProofWrapper
		}
	}
	lockProofCreate sync.RWMutex
}

// ProofCreate calls ProofCreateFunc.
func (mock *ProofsWriterMock) ProofCreate(ctx context.Context, req gopayd.ProofWrapper) error {
	if mock.ProofCreateFunc == nil {
		panic("ProofsWriterMock.ProofCreateFunc: method is nil but ProofsWriter.ProofCreate was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req gopayd.ProofWrapper
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockProofCreate.Lock()
	mock.calls.ProofCreate = append(mock.calls.ProofCreate, callInfo)
	mock.lockProofCreate.Unlock()
	return mock.ProofCreateFunc(ctx, req)
}

// ProofCreateCalls gets all the calls that were made to ProofCreate.
// Check the length with:
//     len(mockedProofsWriter.ProofCreateCalls())
func (mock *ProofsWriterMock) ProofCreateCalls() []struct {
	Ctx context.Context
	Req gopayd.ProofWrapper
} {
	var calls []struct {
		Ctx context.Context
		Req gopayd.ProofWrapper
	}
	mock.lockProofCreate.RLock()
	calls = mock.calls.ProofCreate
	mock.lockProofCreate.RUnlock()
	return calls
}
