skinparam sequenceBoxBackgroundColor White
skinparam sequenceBoxBorderColor SlateGray
skinparam collectionsBackgroundColor WhiteSmoke
skinparam collectionsBorderColor #2f408e
skinparam sequenceLifeLineBorderColor #2f408e
skinparam sequenceLifeLineBackgroundColor WhiteSmoke
skinparam arrowColor #2f408e
skinparam participantBorderColor #2f408e
skinparam participantBackgroundColor WhiteSmoke
skinparam actorBorderColor #2f408e
skinparam actorBackgroundColor WhiteSmoke
skinparam controlBorderColor #2f408e
skinparam controlBackgroundColor WhiteSmoke
skinparam databaseBorderColor #2f408e
skinparam databaseBackgroundColor WhiteSmoke
skinparam entityBorderColor #2f408e
skinparam entityBackgroundColor WhiteSmoke
skinparam boundaryBorderColor #2f408e
skinparam boundaryBackgroundColor WhiteSmoke
skinparam sequenceGroupBorderColor #2f408e
skinparam sequenceGroupBodyBackgroundColor Transparent


skinparam classBackgroundColor WhiteSmoke
skinparam classBorderColor #2f408e
' skinparam classBorderThickness
' skinparam classFontColor
' skinparam classFontName
' skinparam classFontSize
' skinparam classFontStyle
skinparam classHeaderBackgroundColor WhiteSmoke
' skinparam classStereotypeFontColor
' skinparam classStereotypeFontName
' skinparam classStereotypeFontSize
' skinparam classStereotypeFontStyle




'skinparam handwritten true
' ActivityBackgroundColor
' ActivityBarColor
' ActivityBorderColor
' ActivityBorderThickness
' ActivityDiamondBackgroundColor
' ActivityDiamondBorderColor
' ActivityDiamondFontColor
' ActivityDiamondFontName
' ActivityDiamondFontSize
' ActivityDiamondFontStyle
' ActivityEndColor
' ActivityFontColor
' ActivityFontName
' ActivityFontSize
' ActivityFontStyle
' ActivityStartColor
' ActorBackgroundColor
' ActorBorderColor
' ActorFontColor
' ActorFontName
' ActorFontSize
' ActorFontStyle
' ActorStereotypeFontColor
' ActorStereotypeFontName
' ActorStereotypeFontSize
' ActorStereotypeFontStyle
' AgentBackgroundColor
' AgentBorderColor
' AgentFontColor
' AgentFontName
' AgentFontSize
' AgentFontStyle
' AgentStereotypeFontColor
' AgentStereotypeFontName
' AgentStereotypeFontSize
' AgentStereotypeFontStyle
' ArrowColor
' ArrowFontColor
' ArrowFontName
' ArrowFontSize
' ArrowFontStyle
' ArtifactBackgroundColor
' ArtifactBorderColor
' ArtifactFontColor
' ArtifactFontName
' ArtifactFontSize
' ArtifactFontStyle
' ArtifactStereotypeFontColor
' ArtifactStereotypeFontName
' ArtifactStereotypeFontSize
' ArtifactStereotypeFontStyle
' BackgroundColor
' BoundaryBackgroundColor
' BoundaryBorderColor
' BoundaryFontColor
' BoundaryFontName
' BoundaryFontSize
' BoundaryFontStyle
' BoundaryStereotypeFontColor
' BoundaryStereotypeFontName
' BoundaryStereotypeFontSize
' BoundaryStereotypeFontStyle
' CaptionFontColor
' CaptionFontName
' CaptionFontSize
' CaptionFontStyle
' CircledCharacterFontColor
' CircledCharacterFontName
' CircledCharacterFontSize
' CircledCharacterFontStyle
' CircledCharacterRadius
' ClassAttributeFontColor
' ClassAttributeFontName
' ClassAttributeFontSize
' ClassAttributeFontStyle
' ClassAttributeIconSize
' ClassBackgroundColor
' ClassBorderColor
' ClassBorderThickness
' ClassFontColor
' ClassFontName
' ClassFontSize
' ClassFontStyle
' ClassHeaderBackgroundColor
' ClassStereotypeFontColor
' ClassStereotypeFontName
' ClassStereotypeFontSize
' ClassStereotypeFontStyle
' CloudBackgroundColor
' CloudBorderColor
' CloudFontColor
' CloudFontName
' CloudFontSize
' CloudFontStyle
' CloudStereotypeFontColor
' CloudStereotypeFontName
' CloudStereotypeFontSize
' CloudStereotypeFontStyle
' CollectionsBackgroundColor
' CollectionsBorderColor
' ColorArrowSeparationSpace
' ComponentBackgroundColor
' ComponentBorderColor
' ComponentFontColor
' ComponentFontName
' ComponentFontSize
' ComponentFontStyle
' ComponentStereotypeFontColor
' ComponentStereotypeFontName
' ComponentStereotypeFontSize
' ComponentStereotypeFontStyle
' ComponentStyle
' ConditionStyle
' ControlBackgroundColor
' ControlBorderColor
' ControlFontColor
' ControlFontName
' ControlFontSize
' ControlFontStyle
' ControlStereotypeFontColor
' ControlStereotypeFontName
' ControlStereotypeFontSize
' ControlStereotypeFontStyle
' DatabaseBackgroundColor
' DatabaseBorderColor
' DatabaseFontColor
' DatabaseFontName
' DatabaseFontSize
' DatabaseFontStyle
' DatabaseStereotypeFontColor
' DatabaseStereotypeFontName
' DatabaseStereotypeFontSize
' DatabaseStereotypeFontStyle
' DefaultFontColor
' DefaultFontName
' DefaultFontSize
' DefaultFontStyle
' DefaultMonospacedFontName
' DefaultTextAlignment
' DiagramBorderColor
' DiagramBorderThickness
' Dpi
' EntityBackgroundColor
' EntityBorderColor
' EntityFontColor
' EntityFontName
' EntityFontSize
' EntityFontStyle
' EntityStereotypeFontColor
' EntityStereotypeFontName
' EntityStereotypeFontSize
' EntityStereotypeFontStyle
' FileBackgroundColor
' FileBorderColor
' FileFontColor
' FileFontName
' FileFontSize
' FileFontStyle
' FileStereotypeFontColor
' FileStereotypeFontName
' FileStereotypeFontSize
' FileStereotypeFontStyle
' FolderBackgroundColor
' FolderBorderColor
' FolderFontColor
' FolderFontName
' FolderFontSize
' FolderFontStyle
' FolderStereotypeFontColor
' FolderStereotypeFontName
' FolderStereotypeFontSize
' FolderStereotypeFontStyle
' FooterFontColor
' FooterFontName
' FooterFontSize
' FooterFontStyle
' FrameBackgroundColor
' FrameBorderColor
' FrameFontColor
' FrameFontName
' FrameFontSize
' FrameFontStyle
' FrameStereotypeFontColor
' FrameStereotypeFontName
' FrameStereotypeFontSize
' FrameStereotypeFontStyle
' Guillemet
' Handwritten
' HeaderFontColor
' HeaderFontName
' HeaderFontSize
' HeaderFontStyle
' HyperlinkColor
' HyperlinkUnderline
' IconIEMandatoryColor
' IconPackageBackgroundColor
' IconPackageColor
' IconPrivateBackgroundColor
' IconPrivateColor
' IconProtectedBackgroundColor
' IconProtectedColor
' IconPublicBackgroundColor
' IconPublicColor
' InterfaceBackgroundColor
' InterfaceBorderColor
' InterfaceFontColor
' InterfaceFontName
' InterfaceFontSize
' InterfaceFontStyle
' InterfaceStereotypeFontColor
' InterfaceStereotypeFontName
' InterfaceStereotypeFontSize
' InterfaceStereotypeFontStyle
' LegendBackgroundColor
' LegendBorderColor
' LegendBorderThickness
' LegendFontColor
' LegendFontName
' LegendFontSize
' LegendFontStyle
' Linetype
' MaxAsciiMessageLength
' MaxMessageSize
' MinClassWidth
' Monochrome
' NodeBackgroundColor
' NodeBorderColor
' NodeFontColor
' NodeFontName
' NodeFontSize
' NodeFontStyle
' NodeStereotypeFontColor
' NodeStereotypeFontName
' NodeStereotypeFontSize
' NodeStereotypeFontStyle
' Nodesep
' NoteBackgroundColor
' NoteBorderColor
' NoteBorderThickness
' NoteFontColor
' NoteFontName
' NoteFontSize
' NoteFontStyle
' NoteShadowing
' ObjectAttributeFontColor
' ObjectAttributeFontName
' ObjectAttributeFontSize
' ObjectAttributeFontStyle
' ObjectBackgroundColor
' ObjectBorderColor
' ObjectBorderThickness
' ObjectFontColor
' ObjectFontName
' ObjectFontSize
' ObjectFontStyle
' ObjectStereotypeFontColor
' ObjectStereotypeFontName
' ObjectStereotypeFontSize
' ObjectStereotypeFontStyle
' PackageBackgroundColor
' PackageBorderColor
' PackageBorderThickness
' PackageFontColor
' PackageFontName
' PackageFontSize
' PackageFontStyle
' PackageStereotypeFontColor
' PackageStereotypeFontName
' PackageStereotypeFontSize
' PackageStereotypeFontStyle
' PackageStyle
' Padding
' ParticipantBackgroundColor
' ParticipantBorderColor
' ParticipantFontColor
' ParticipantFontName
' ParticipantFontSize
' ParticipantFontStyle
' PartitionBackgroundColor
' PartitionBorderColor
' PartitionBorderThickness
' PartitionFontColor
' PartitionFontName
' PartitionFontSize
' PartitionFontStyle
' QueueBackgroundColor
' QueueBorderColor
' QueueFontColor
' QueueFontName
' QueueFontSize
' QueueFontStyle
' QueueStereotypeFontColor
' QueueStereotypeFontName
' QueueStereotypeFontSize
' QueueStereotypeFontStyle
' Ranksep
' RectangleBackgroundColor
' RectangleBorderColor
' RectangleBorderThickness
' RectangleFontColor
' RectangleFontName
' RectangleFontSize
' RectangleFontStyle
' RectangleStereotypeFontColor
' RectangleStereotypeFontName
' RectangleStereotypeFontSize
' RectangleStereotypeFontStyle
' RoundCorner
' SameClassWidth
' SequenceActorBorderThickness
' SequenceArrowThickness
' SequenceBoxBackgroundColor
' SequenceBoxBorderColor
' SequenceBoxFontColor
' SequenceBoxFontName
' SequenceBoxFontSize
' SequenceBoxFontStyle
' SequenceDelayFontColor
' SequenceDelayFontName
' SequenceDelayFontSize
' SequenceDelayFontStyle
' SequenceDividerBackgroundColor
' SequenceDividerBorderColor
' SequenceDividerBorderThickness
' SequenceDividerFontColor
' SequenceDividerFontName
' SequenceDividerFontSize
' SequenceDividerFontStyle
' SequenceGroupBackgroundColor
' SequenceGroupBodyBackgroundColor
' SequenceGroupBorderColor
' SequenceGroupBorderThickness
' SequenceGroupFontColor
' SequenceGroupFontName
' SequenceGroupFontSize
' SequenceGroupFontStyle
' SequenceGroupHeaderFontColor
' SequenceGroupHeaderFontName
' SequenceGroupHeaderFontSize
' SequenceGroupHeaderFontStyle
' SequenceLifeLineBackgroundColor
' SequenceLifeLineBorderColor
' SequenceLifeLineBorderThickness
' SequenceNewpageSeparatorColor
' SequenceParticipant
' SequenceParticipantBorderThickness
' SequenceReferenceBackgroundColor
' SequenceReferenceBorderColor
' SequenceReferenceBorderThickness
' SequenceReferenceFontColor
' SequenceReferenceFontName
' SequenceReferenceFontSize
' SequenceReferenceFontStyle
' SequenceReferenceHeaderBackgroundColor
' SequenceStereotypeFontColor
' SequenceStereotypeFontName
' SequenceStereotypeFontSize
' SequenceStereotypeFontStyle
' SequenceTitleFontColor
' SequenceTitleFontName
' SequenceTitleFontSize
' SequenceTitleFontStyle
' Shadowing
' StackBackgroundColor
' StackBorderColor
' StackFontColor
' StackFontName
' StackFontSize
' StackFontStyle
' StackStereotypeFontColor
' StackStereotypeFontName
' StackStereotypeFontSize
' StackStereotypeFontStyle
' StateAttributeFontColor
' StateAttributeFontName
' StateAttributeFontSize
' StateAttributeFontStyle
' StateBackgroundColor
' StateBorderColor
' StateEndColor
' StateFontColor
' StateFontName
' StateFontSize
' StateFontStyle
' StateStartColor
' StereotypeABackgroundColor
' StereotypeCBackgroundColor
' StereotypeEBackgroundColor
' StereotypeIBackgroundColor
' StereotypeNBackgroundColor
' StereotypePosition
' StorageBackgroundColor
' StorageBorderColor
' StorageFontColor
' StorageFontName
' StorageFontSize
' StorageFontStyle
' StorageStereotypeFontColor
' StorageStereotypeFontName
' StorageStereotypeFontSize
' StorageStereotypeFontStyle
' Style
' SvglinkTarget
' SwimlaneBorderColor
' SwimlaneBorderThickness
' SwimlaneTitleFontColor
' SwimlaneTitleFontName
' SwimlaneTitleFontSize
' SwimlaneTitleFontStyle
' TabSize
' TitleBackgroundColor
' TitleBorderColor
' TitleBorderRoundCorner
' TitleBorderThickness
' TitleFontColor
' TitleFontName
' TitleFontSize
' TitleFontStyle
' UsecaseBackgroundColor
' UsecaseBorderColor
' UsecaseBorderThickness
' UsecaseFontColor
' UsecaseFontName
' UsecaseFontSize
' UsecaseFontStyle
' UsecaseStereotypeFontColor
' UsecaseStereotypeFontName
' UsecaseStereotypeFontSize
' UsecaseStereotypeFontStyle